<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><?= $this->user->login; ?> GitHub information</h1>
    </div>
</div>

<div class="col-lg-4">
    <div class="panel panel-default">
        <div class="panel-heading">
            <i class="fa fa-user fa-fw"></i> <?= $this->user->name; ?>
        </div>
        <div class="panel-body center">
            <div class="panel" style="text-align: center">
                <img width="240" class="img-circle" src="<?= $this->user->avatar_url; ?>" alt="<?= $this->user->login; ?>" />
            </div>
            <a href="#" class="btn btn-default btn-block">View Details</a>
        </div>
    </div>
</div>


<div class="col-lg-8">
    <div class="panel panel-default">
        <div class="panel-heading">
            <i class="fa fa-bell fa-fw"></i> GitHub User Panel
        </div>
        <!-- /.panel-heading -->
        <div class="panel-body">
            <div class="list-group">
                <a href="#" class="list-group-item">
                    <i class="fa fa-comment fa-fw"></i> Name:
                    <span class="pull-right text-muted small"><em><?= $this->user->name; ?></em>
                    </span>
                </a>
                <a href="#" class="list-group-item">
                    <i class="fa fa-twitter fa-fw"></i> Login:
                    <span class="pull-right text-muted small"><em><?= $this->user->login; ?></em>
                    </span>
                </a>
                <a href="#" class="list-group-item">
                    <i class="fa fa-envelope fa-fw"></i> Github url:
                    <span class="pull-right text-muted">
                        <?= $this->user->html_url; ?>
                    </span>
                </a>
                <a href="#" class="list-group-item">
                    <i class="fa fa-tasks fa-fw"></i> Company:
                    <span class="pull-right text-muted small"><em><?= $this->user->company; ?></em>
                    </span>
                </a>
                <a href="#" class="list-group-item">
                    <i class="fa fa-upload fa-fw"></i> Location:
                    <span class="pull-right text-muted small"><em><?= $this->user->location; ?></em>
                    </span>
                </a>
                <a href="#" class="list-group-item">
                    <i class="fa fa-bolt fa-fw"></i> Type:
                    <span class="pull-right text-muted small"><em><?= $this->user->type; ?></em>
                    </span>
                </a>
                <a href="#" class="list-group-item">
                    <i class="fa fa-warning fa-fw"></i> Created at:
                    <span class="pull-right text-muted small"><em><?= $this->user->created_at; ?></em>
                    </span>
                </a>
                <a href="#" class="list-group-item">
                    <i class="fa fa-shopping-cart fa-fw"></i> Updated at:
                    <span class="pull-right text-muted small"><em><?= $this->user->updated_at; ?></em>
                    </span>
                </a>
                <a href="#" class="list-group-item">
                    <i class="fa fa-money fa-fw"></i> Disk usage:
                    <span class="pull-right text-muted small"><em><?= $this->user->disk_usage; ?></em>
                    </span>
                </a>
            </div>
            <!-- /.list-group -->
        </div>
        <!-- /.panel-body -->
    </div>
    <!-- /.panel -->
</div>
<!-- /.col-lg-8 -->